name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        python app.py

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v2.6.0
      with:
        config: false

        70b31d4 (Finalized CI/CD pipeline with Semgrep and Gitleaks)
